### ISSUE TITLE
Openvpn not calling plugin

### ISSUE THREAD

**Issue by tc-covata** [okta/okta-openvpn#7]
Hi, 

Not sure what I'm missing bit

- Running Openvpn + Okta plugin with our production Okta Instance

Requirements in README for this project say

- OpenVPN must be configured to call plugins via a deferred call.

How do I ensure that is happening?

**Comment by tc-covata** [comment]
I also seeing the following errors in the openvpn log, when my user tries to authenticate using their Okta username and password + mfa code

```
Traceback (most recent call last):
  File "/usr/lib/openvpn/plugins/okta_openvpn.py", line 391, in <module>
    validator.run()
  File "/usr/lib/openvpn/plugins/okta_openvpn.py", line 379, in run
    self.write_result_to_control_file()
  File "/usr/lib/openvpn/plugins/okta_openvpn.py", line 361, in write_result_to_control_file
    self.check_control_file_permissions()
  File "/usr/lib/openvpn/plugins/okta_openvpn.py", line 341, in check_control_file_permissions
    file_mode = os.stat(self.control_file).st_mode
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by joelfranusic-okta** [comment]
It looks like the Okta plugin is being called. However, it looks like there is an issue with the "control file" which OpenVPN uses to communicate with the plugin. 

What is `tmp-dir` set to in your `server.conf`? Have you made sure that [the directory exists and that the permissions have been set correctly on that directory](https://github.com/okta/okta-openvpn#make-sure-that-openvpn-has-a-tempory-directory)?

If the directory exists and has permissions set up correctly, could you [run the Okta OpenVPN plugin tests](https://github.com/okta/okta-openvpn#testing) and let me know what you see?

**Comment by tc-covata** [comment]
Thanks for getting back. 

tmp-dir "/etc/openvpn/tmp"

Does server.conf need any of the following lines uncommented? Was not totally sure what is required to get this plugin 'loaded'

#plugin /usr/lib/openvpn/plugins/defer_simple.so /usr/lib/openvpn/plugins/okta_openvpn.py
#auth-user-pass-verify /usr/lib/openvpn/plugins/okta_openvpn.py via-file

**Comment by tc-covata** [comment]
Also, when i run nosetests, one failure i see is

`okta_openvpn: CRITICAL: Refusing to authenticate because host covata.okta.com failed a TLS public key pinning check. Please contact support@okta.com with this error message
okta_openvpn: ERROR: Error connecting to the Okta API: Public Key not found in pinset!`

**Comment by tc-covata** [comment]
Actually, all good, I now have it working. 
I was missing 744 on the /etc/openvpn/tmp file (I had 644 which I thought would be ok, but obviously not)

Great work on the plugin, thanks.

**Comment by joelfranusic-okta** [comment]
Glad to hear it! 

For others that might have a similar issue in the future, the solution was that @tc-covata needed to have the permissions on the `/etc/openvpn/tmp` directory set to `744` (`drwxr--r--`) instead of 644 (`drw-r--r--`) - the reason for this is that the execute bit (`x`) on directories is what allows processes to "descend" or "`cd`" into a directory.
