### ISSUE TITLE
Unexpected error with the Okta API: a float is required

### ISSUE THREAD

**Issue by timm088** [okta/okta-openvpn#9]
When using the latest master version i receive the following error in the okta_openvpn.log

`Unexpected error with the Okta API: a float is required`

User authenticates with their login and password, but receives no push notification.

**Comment by joelfranusic-okta** [comment]
Can you give me more details about what version you are using? I'm most interested in the outputs from these commands:

$ `git rev-parse HEAD`
$ `grep 'version = ' okta_openvpn.py`

**Comment by timm088** [comment]
# git rev-parse HEAD
a0d1f97d6fa390b2acd2e97dd19947d602f00dd3
# grep 'version = ' okta_openvpn.py
version = "0.10.1-beta"

I do receive the push notification, but the process fails before that. 

Does client matter? Using Tunnelblick

**Comment by timm088** [comment]
I have also destroyed the whole repository, and plugin installation and re-run build steps. 
Same result 
`Unexpected error with the Okta API: a float is required
`

**Comment by joelfranusic-okta** [comment]
This is likely an error in the code. Any tips on how I might try to replicate your setup for testing purposes? (What OS are you running? What version? What version of OpenVPN?)

**Comment by timm088** [comment]
Thanks for the response

```
OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Feb  2 2016
library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08

O/S Is ubuntu 16.04.2 LTS
Linux Kernel 4.4.0-66-generic
```

**Comment by joelfranusic-okta** [comment]
Cool, thanks! I'll be looking at this tomorrow.

**Comment by joelfranusic-okta** [comment]
I'm in the middle of getting an other OpenVPN server set up to try and reproduce, though I got pulled into another project. I'm hoping to make progress here tomorrow.

**Comment by covataamos** [comment]
Thanks for the update. Appreciate your work.

**Comment by joelfranusic-okta** [comment]
Update: I was just able to reproduce the issue described above! Now to do some debugging.

**Comment by joelfranusic-okta** [comment]
I found the issue. The implementation of `time.sleep()` is OS dependent. Mac OS X is okay with a an `int` but Linux requires a `float`. I have a patch here: https://github.com/okta/okta-openvpn/tree/0.10.2-beta and will merge into master once I get my code reviewed.

**Comment by joelfranusic-okta** [comment]
@timm088 and/or @covataamos - if you are comfortable with pulling the code from my PR, I'd appreciate knowing if my fix works for you.

**Comment by covataamos** [comment]
Sorry we were out of office today. Will try to get to it tomorrow.

**Comment by timm088** [comment]
Tested and working (with push notification), thanks!

```
okta_openvpn-MainProcess[3067]: okta_openvpn: Authenticating username user@mydomain.com
user@mydomain.com password validates, checking second factor
okta_openvpn-MainProcess[3067]: okta_openvpn: User user@mydomain.com is now authenticated with MFA via Okta API
```

**Comment by jonjohnston** [comment]
I know this thread is old but the link is not working to your fix and the current version has same issue
